[package]
name = "pp-rs"
version = "0.1.0"
authors = ["pp-rs Developers"]
description = "Shader preprocessor"
homepage = "https://github.com/Kangz/glslpp-rs"
repository = "https://github.com/Kangz/glslpp-rs"
keywords = ["shader", "preprocessor", "glsl"]
license = "BSD-3-Clause"

[dependencies]
